# Expected Variables
# TAG - Tag or version of the containers
version: '2'
services:
  controller:
    image: 10.84.34.155:5000/contrail-controller-liberty:${TAG}
    privileged: true
    network_mode: host
    pid: "host"
    cap_add:
      - AUDIT_WRITE
    environment:
      - CLOUD_ORCHESTRATOR=kubernetes
  analytics:
    image: 10.84.34.155:5000/contrail-analytics-liberty:${TAG}
    privileged: true
    network_mode: host
    pid: "host"
    cap_add:
      - AUDIT_WRITE
    depends_on:
     - controller
    environment:
      - CLOUD_ORCHESTRATOR=kubernetes
  agent:
    image: 10.84.34.155:5000/contrail-agent-liberty:${TAG}
    privileged: true
    network_mode: host
    pid: "host"
    volumes:
      - /usr/src:/usr/src
      - /lib/modules:/lib/modules
    cap_add:
      - AUDIT_WRITE
    depends_on:
     - controller
     - analytics
    environment:
      - CLOUD_ORCHESTRATOR=kubernetes