apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "agent.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "agent.fullname" . }}
        contrail_function: "contrail-vrouter"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: DoesNotExist
              - key: "contrail.role"
                operator: "NotIn"
                values: 
                - controller
      hostNetwork: true
      containers:
      - name: contrail-agent
        image: "{{ .Values.imageRepo }}/{{ default "contrail-agent" .Values.agentImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: etc-contrailctl
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /usr/src
          name: usr-src
        - mountPath: /host/opt_cni_bin
          name: opt-cni-bin
        - mountPath: /host/etc_cni
          name: etc-cni
        - mountPath: /var/lib/contrail/
          name: contrail-varlib
        # This is a workaround just to make sure the directory is created on host
        - mountPath: /var/log/contrail/cni
          name: log-cni
      volumes:
      - name: etc-contrailctl
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: agent-config
            path: agent.conf
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: etc-cni
        hostPath:
          path: /etc/cni
      - name: contrail-varlib
        hostPath:
          path: /var/lib/contrail/
      - name: log-cni
        hostPath:
          path: /var/log/contrail/cni/
