apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "agent.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "agent.fullname" . }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "kubeadm.alpha.kubernetes.io/role",
                        "operator": "NotIn",
                        "values": ["master"]
                      }
                    ]
                  }
                ]
              }
            }
          }
        scheduler.alpha.kubernetes.io/tolerations: >
          [
            {
              "key":"dedicated",
              "value":"master",
              "effect":"NoSchedule"
            },
           {
              "key":"CriticalAddonsOnly",
              "operator":"Exists"
           }
          ]
    spec:
      hostNetwork: true
      containers:
      - name: contrail-agent
        image: "{{ .Values.imageRepo }}/{{ default "contrail-agent" .Values.agentImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: etc-contrailctl
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /usr/src
          name: usr-src
        - mountPath: /host/opt_cni_bin
          name: opt-cni-bin
        - mountPath: /host/etc_cni
          name: etc-cni
      volumes:
      - name: etc-contrailctl
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: agent-config
            path: agent.conf
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: etc-cni
        hostPath:
          path: /etc/cni
