apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
data:
  agent-config: |
    [GLOBAL]
    vrouter_physical_interface = {{ .Values.vrouterPhysicalInterface | quote }}
    controller_list = {{ .Values.controllerList }}
    analytics_list = {{ .Values.analyticsList }}
