apiVersion: v1
kind: ConfigMap
metadata:
  name: contrailctl-config
  labels:
    app: contrail-cni
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
  namespace: kube-system
data:
  agent-config: |-
{{ include "globalConfig" .Values | indent 4 }}
{{ include "agentConfig" .Values | indent 4 }}
  controller-config: |-
{{ include "globalConfig" .Values | indent 4 }}
{{ include "webuiConfig" .Values | indent 4 }}
  analyticsdb-config: |-
{{ include "globalConfig" .Values | indent 4 }}
  analytics-config: |-
{{ include "globalConfig" .Values | indent 4 }}
  kube-manager-config: |-
{{ include "globalConfig" .Values | indent 4 }}
{{ include "kubernetesConfig" .Values | indent 4 }}
