{{ if .Values.contrailHA }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "controller.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "controller.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "controller.fullname" . }}
        contrail_function: "contrail-controller"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "contrail.role"
                operator: In
                values:
                - controller
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-controller
        image: "{{ .Values.imageRepo }}/{{ default "contrail-controller" .Values.controllerImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-controller
        - mountPath: /var/lib/cassandra
          name: configdb-data
        - mountPath: /var/lib/zookeeper
          name: zookeeper-data
      volumes:
      - name: contrailctl-controller
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: controller-config
            path: controller.conf
      - name: configdb-data
        emptyDir: {}
      - name: zookeeper-data
        emptyDir: {}
{{ end }}
