{{ if .Values.contrailHA }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "kubemanager.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "kubemanager.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "kubemanager.fullname" . }}
        contrail_function: "contrail-controller"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "contrail.role"
                operator: In
                values:
                - controller
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-kube-manager
        image: "{{ .Values.imageRepo }}/{{ default "contrail-kube-manager" .Values.kubeManagerImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-kube-manager
      volumes:
      - name: contrailctl-kube-manager
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: kube-manager-config
            path: kubemanager.conf
{{ end }}
