# Default values for contrail.
# contrailVersion - example 4.0.0.0-3042
# This variable cannot be blank.
# contrailVersion:

# osRelease - operating system release
# ubuntu 14.04 - u14.04
# ubuntu 16.04 - u16.04
# centos 7.1 - c7.1
# centos 7.2 - c7.2
osRelease: u16.04

# image repository, pull policy etc
imageRepo: 10.84.34.155:5000

#
# Global configurations
#
global:
  # controller_list - list of controller nodes
  controller_list: '["192.168.0.109"]'

  # analytics_list - list of analytics nodes
  analytics_list: '["192.168.0.109"]'

  # cloud_orchestrator: values - kubernetes, mesos, openshift, openstack
  cloud_orchestrator: kubernetes

#
# Controller configurations
#

#
# webui configurations
#
webui:
  # http listen port: default 8080
  http_listen_port: 8085

  # https_listen_port: default 8143
  # https_listen_port:

#
# agent configurations
#
agent:
  # vrouter_physical_interface - physical interface to use for vrouter
  vrouter_physical_interface: eth0

#
# Other optional parameters which rarely changed
#

## Specify a imagePullPolicy: 'Always' if imageTag is 'latest', else set to 'IfNotPresent'.
## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

# container image names
# controllerImageName: contrail-controller
# analyticsImageName: contrail-analytics
# analyticsdbImageName: contrail-analyticsdb
# kubeManagerImageName: contrail-kube-manager
# agentImageName: contrail-agent
